Feature/how we do
codewarrior94/hell_en_project pull request #14
Opened 2021-04-03 18:56 UTC by IvanTarelnik

Дима, проверь, пожалуйста, особенно по брейкпоинтам посмотри всё ли правильно.

2021-04-03 19:11 UTC, codewarrior94 commented on src/sass/layout/_how-we-do.scss
> +    width: 1345px;
такая и остаеться, падинг 0 15пх

2021-04-03 19:12 UTC, codewarrior94 requested changes

2021-04-03 19:12 UTC, codewarrior94 commented on src/sass/layout/_how-we-do.scss
> -    width: 1315px;
Оставляй, такое значение, на десктопе падинг 15

2021-04-03 20:29 UTC, IvanTarelnik commented on src/sass/layout/_how-we-do.scss
> -    width: 1315px;
Исправить ширину контейнера если ширина вивпорта 1315, с 1345 на 1315 ? Если пропишу 1315 ширину у меня ширина карточек будет не 425, а каждая карточка уменьшится на 10рх, из-за наличия двух паддингов по 15рх, всё равно исправлять ?

2021-04-03 20:30 UTC, IvanTarelnik commented on src/sass/layout/_how-we-do.scss
> -    width: 1315px;
тогда появится несоответствие с макетом

2021-04-04 13:44 UTC, codewarrior94 approved these changes

2021-04-04 13:44 UTC, merged